let monrovia_twilight_theme = {
   binary: "#d8a594"
   block: "#abb1bb"
   bool: "#e3beb2"
   cellpath: "#e5e9f0"
   date: "#a3be8c"
   duration: "#a3be8c"
   filesize: "#d8a594"
   float: "#d8a594"
   int: "#d8a594"
   list: "#abb1bb"
   nothing: "#e5e9f0"
   range: "#e5e9f0"
   record: "#e5e9f0"
   string: "#a3be8c"

   leading_trailing_space_bg: "#3c4353"
   header: "#abb1bb"
   empty: "#81a1c1"
   row_index: "#aeb0b4"
   hints: "#aeb0b4"
   separator: "#b1bbc8"

   shape_block: "#abb1bb"
   shape_bool: "#e3beb2"
   shape_external: "#b48ead"
   shape_externalarg: "#e5e9f0"
   shape_filepath: "#e5e9f0"
   shape_flag: "#88c0d0"
   shape_float: "#d8a594"
   shape_globpattern: "#f0d399"
   shape_int: "#d8a594"
   shape_internalcall: "#b48ead"
   shape_list: "#abb1bb"
   shape_literal: "#a3be8c"
   shape_nothing: "#93ccdc"
   shape_operator: "#abb1bb"
   shape_record: "#abb1bb"
   shape_string: "#a3be8c"
   shape_string_interpolation: "#f0d399"
   shape_table: "#abb1bb"
   shape_variable: "#e5e9f0"
}
