# Monrovia colors for Kitty
## name: monrovia_dawn
## upstream: https://github.com/tkolleh/monrovia.nvim/raw/main/extra/monrovia_dawn/kitty.conf

background #fcf8f3
foreground #2b293c
selection_background #d0d8d8
selection_foreground #2b293c
cursor_text_color #fcf8f3
url_color #547565

# Cursor
# uncomment for reverse background
# cursor none
cursor #2b293c

# Border
active_border_color #286983
inactive_border_color #bdbfc9
bell_border_color #98591b

# Tabs
active_tab_background #286983
active_tab_foreground #ebe5df
inactive_tab_background #d0d8d8
inactive_tab_foreground #5d4f64

# normal
color0 #575279
color1 #a85169
color2 #547565
color3 #9e6310
color4 #286983
color5 #7b6298
color6 #44757e
color7 #e5e9f0

# bright
color8 #5f5695
color9 #b4647a
color10 #618774
color11 #ba7413
color12 #2d81a3
color13 #8b73a5
color14 #4f8892
color15 #e6ebf3

# extended colors
color16 #98591b
color17 #b73e7c
