[metadata]
name = "monrovia_dawn"
author = "tkolleh"
origin_url = "https://github.com/tkolleh/monrovia.nvim"

[colors]
foreground = "#2b293c"
background = "#fcf8f3"
cursor_bg = "#2b293c"
cursor_border = "#2b293c"
cursor_fg = "#fcf8f3"
compose_cursor = '#98591b'
selection_bg = "#d0d8d8"
selection_fg = "#2b293c"
scrollbar_thumb = "#2c2932"
split = "#ebe5df"
visual_bell = "#2b293c"
ansi = ["#575279", "#a85169", "#547565", "#9e6310", "#286983", "#7b6298", "#44757e", "#e5e9f0"]
brights = ["#5f5695", "#b4647a", "#618774", "#ba7413", "#2d81a3", "#8b73a5", "#4f8892", "#e6ebf3"]

[colors.indexed]
16 = "#b73e7c"
17 = "#98591b"

[colors.tab_bar]
background = "#ebe5df"
inactive_tab_edge = "#ebe5df"
inactive_tab_edge_hover = "#e6ded6"

[colors.tab_bar.active_tab]
bg_color = "#2c2932"
fg_color = "#fcf8f3"
intensity = "Normal"
italic = false
strikethrough = false
underline = "None"

[colors.tab_bar.inactive_tab]
bg_color = "#e6ded6"
fg_color = "#4c4869"
intensity = "Normal"
italic = false
strikethrough = false
underline = "None"

[colors.tab_bar.inactive_tab_hover]
bg_color = "#f2ebe3"
fg_color = "#2b293c"
intensity = "Normal"
italic = false
strikethrough = false
underline = "None"

[colors.tab_bar.new_tab]
bg_color = "#fcf8f3"
fg_color = "#4c4869"
intensity = "Normal"
italic = false
strikethrough = false
underline = "None"

[colors.tab_bar.new_tab_hover]
bg_color = "#f2ebe3"
fg_color = "#2b293c"
intensity = "Normal"
italic = false
strikethrough = false
underline = "None"

