let monrovia_sunset_theme = {
   binary: "#ff8349"
   block: "#cbd9d8"
   bool: "#ff9664"
   cellpath: "#ebebeb"
   date: "#7aa4a1"
   duration: "#7aa4a1"
   filesize: "#ff8349"
   float: "#ff8349"
   int: "#ff8349"
   list: "#cbd9d8"
   nothing: "#ebebeb"
   range: "#ebebeb"
   record: "#ebebeb"
   string: "#7aa4a1"

   leading_trailing_space_bg: "#1f373c"
   header: "#cbd9d8"
   empty: "#5a93aa"
   row_index: "#7da2a2"
   hints: "#7da2a2"
   separator: "#9da9b2"

   shape_block: "#cbd9d8"
   shape_bool: "#ff9664"
   shape_external: "#ad5c7c"
   shape_externalarg: "#ebebeb"
   shape_filepath: "#ebebeb"
   shape_flag: "#a1cdd8"
   shape_float: "#ff8349"
   shape_globpattern: "#fdb292"
   shape_int: "#ff8349"
   shape_internalcall: "#ad5c7c"
   shape_list: "#cbd9d8"
   shape_literal: "#7aa4a1"
   shape_nothing: "#afd4de"
   shape_operator: "#cbd9d8"
   shape_record: "#cbd9d8"
   shape_string: "#7aa4a1"
   shape_string_interpolation: "#fdb292"
   shape_table: "#cbd9d8"
   shape_variable: "#ebebeb"
}
