[metadata]
name = "monrovia_day"
author = "tkolleh"
origin_url = "https://github.com/tkolleh/monrovia.nvim"

[colors]
foreground = "#3d2b5a"
background = "#f9f6f2"
cursor_bg = "#3d2b5a"
cursor_border = "#3d2b5a"
cursor_fg = "#f9f6f2"
compose_cursor = '#8b4d1d'
selection_bg = "#e7d2be"
selection_fg = "#3d2b5a"
scrollbar_thumb = "#42272f"
split = "#e4dcd4"
visual_bell = "#3d2b5a"
ansi = ["#352c24", "#a5222f", "#396847", "#ac5402", "#2848a9", "#6e33ce", "#287980", "#f2e9e1"]
brights = ["#534c45", "#b3434e", "#577f63", "#b86e28", "#4863b6", "#8452d5", "#488d93", "#f4ece6"]

[colors.indexed]
16 = "#a440b5"
17 = "#8b4d1d"

[colors.tab_bar]
background = "#e4dcd4"
inactive_tab_edge = "#e4dcd4"
inactive_tab_edge_hover = "#e0d5c8"

[colors.tab_bar.active_tab]
bg_color = "#42272f"
fg_color = "#f9f6f2"
intensity = "Normal"
italic = false
strikethrough = false
underline = "None"

[colors.tab_bar.inactive_tab]
bg_color = "#e0d5c8"
fg_color = "#643f61"
intensity = "Normal"
italic = false
strikethrough = false
underline = "None"

[colors.tab_bar.inactive_tab_hover]
bg_color = "#ebe3da"
fg_color = "#3d2b5a"
intensity = "Normal"
italic = false
strikethrough = false
underline = "None"

[colors.tab_bar.new_tab]
bg_color = "#f9f6f2"
fg_color = "#643f61"
intensity = "Normal"
italic = false
strikethrough = false
underline = "None"

[colors.tab_bar.new_tab_hover]
bg_color = "#ebe3da"
fg_color = "#3d2b5a"
intensity = "Normal"
italic = false
strikethrough = false
underline = "None"

